LibrosBundle\Entity\Idioma:
    type: entity
    table: idiomas
    repositoryClass: LibrosBundle\Repository\IdiomaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '30'
            unique: true

    oneToMany:
        libros:
            targetEntity: Libro 
            mappedBy: idioma
    lifecycleCallbacks: {  }
