<?php

namespace LibrosBundle\Repository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends \Doctrine\ORM\EntityRepository {
	//este lo hice yo
	public function create($unaCategoria) {
		$em = $this->getEntityManager();
		$em = persist($unaCategoria);
	}
}
