<?php

namespace LibrosBundle\Repository;

/**
 * LibroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibroRepository extends \Doctrine\ORM\EntityRepository {
	public function buscar($tituloLibro) {

		$em = $this->getEntityManager();
		$query = $this->createQueryBuilder("libros")
			->where("libros.titulo like :tituloLibro")
			->setParameter("tituloLibro", "%$tituloLibro%")
			->getQuery();
		$libros = $query->getResult();
		return $libros;
	}
}
