<?php

namespace LibrosBundle\Repository;

/**
 * LibroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibroRepository extends \Doctrine\ORM\EntityRepository {
	public function buscar($criterios) {

		$em = $this->getEntityManager();
		$query = $this->createQueryBuilder("libros");

		if (isset($criterios['busqueda'])) {
			$query
				->where("libros.titulo like :tituloLibro")
				->setParameter("tituloLibro", "%{$criterios['busqueda']}%");
		}

		if (isset($criterios['categoria']) && !$criterios['categoria']->isEmpty()) {
			$query
				->innerJoin('libros.categoria', 'c')
				->andWhere($query->expr()->in('c', ':categoria'))
				->setParameter('categoria', $criterios['categoria']);

		}

		return $query->getQuery()->getResult();
	}

	public function buscarApi($criterios) {

		$em = $this->getEntityManager();
		$query = $this->createQueryBuilder("libros");

		if (isset($criterios)) {
			$query
				->where("libros.titulo like :tituloLibro")
				->setParameter("tituloLibro", "%{$criterios}%");
		}

		return $query->getQuery()->getResult();
	}
}
